os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - libarmadillo-dev
      - libopenblas-dev

install:
  # Fix GTest problem with symbolic links 
  - DIR=$(pwd)
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $DIR

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j8
  - src/types2/matrixTestsRunner
  - src/types2/matrixArrayTestsRunner
  - src/optimization/artificialLandscapesTestsRunner
  - src/optimization/optimizationFunctionsTestsRunner
  - src/loss/lossTestsRunner
  - src/feed_forward/fully_connected/FullyConnectedLayerTestsRunner
